### ISSUE TITLE
module declares its path as: github.com/securego/gosec

### ISSUE THREAD

**Issue by jtorvald** [gnieto/mulint#1]
$ go get -u github.com/gnieto/mulint

go: github.com/gnieto/mulint upgrade => v0.0.0-20180313231918-24ec3193fbeb
go: finding module for package github.com/GoASTScanner/gas
go: found github.com/GoASTScanner/gas in github.com/GoASTScanner/gas v0.0.0-20200401082031-e946c8c39989
go: github.com/gnieto/mulint imports
	github.com/gnieto/mulint/mulint imports
	github.com/GoASTScanner/gas: github.com/GoASTScanner/gas@v0.0.0-20200401082031-e946c8c39989: parsing go.mod:
	module declares its path as: github.com/securego/gosec
	        but was required as: github.com/GoASTScanner/gas

**Comment by gnieto** [comment]
Hi @jtorvald 

Sorry for the late reply. I've updated the project in order to be able to install it via `go get`.

To be honest, this was a toy project I did some years ago and it was a little bit unmaintained. Please, let me know if you can run it now or if you find this lint useful.

Thanks!
